### PR TITLE
Strecth proportional => Fit

### PR DESCRIPTION
**Pull request by whismerhill**
Translation according to windows standard

if you don't agree it's fine by me, you can just close it. Just thought I would point that out.

### CODE REVIEW

**Comment by whismerhill** [comment]
if you don't agree it's fine by me, you can just close it. Just thought I would point that out.

**Comment by mistic100** [comment]
If you only change the source ts file it will break, you also have to edit the corresponding cpp files and the ts files in other languages.

**Comment by whismerhill** [comment]
ho I didn't know I just thought it was a language translation file

**Comment by whismerhill** [comment]
is that all ?

**Pull request merged**
